# Generated by Django 3.2.18 on 2023-03-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='email', max_length=254, verbose_name='El. paštas'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='EmployeeUser',
        ),
    ]
