# Generated by Django 3.2.18 on 2023-03-01 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_manager', '0002_auto_20230301_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
